### PR TITLE
Update Runtime(s) to 23.08

### PR DESCRIPTION
**Pull request by Justinzobel**

### CODE REVIEW

**Comment by tsdgeos** [comment]
@twelho if this compiles (hopefully it will) can you confirm your changes in https://github.com/flathub/org.kde.kile/pull/210 still work here?

**Comment by Justinzobel** [comment]
Thanks for sorting this out. I haven't had the time lately to investigate. I think there are a few with the gnustep failure, so this patch if it works should be able to be applied there.

**Comment by tsdgeos** [comment]
@twelho please test

**Comment by twelho** [comment]
Does not run with https://github.com/flathub/org.kde.kile/pull/210 merged:

```
$ flatpak run org.kde.kile 
kile: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
```

**Comment by twelho** [comment]
Update: not a problem of https://github.com/flathub/org.kde.kile/pull/210, the changes in PR do not work regardless of https://github.com/flathub/org.kde.kile/pull/210 being merged or not.

**Comment by tsdgeos** [comment]
@twelho can you give it a try now? It starts for me but i don't really know how to use kile (i forgot latex like 20 years ago ^_^)

**Comment by twelho** [comment]
Sorry for the delay, can confirm that it works now. My (relatively complex) documents render out-of-the-box without issues. Needed to spin my own build from this branch though, since the build above has expired, but I'm definitely on 23.08 now:

```
$ flatpak --user info org.kde.kile 

Kile - TeX/LaTeX Editor

          ID: org.kde.kile
         Ref: app/org.kde.kile/x86_64/master
        Arch: x86_64
      Branch: master
     Version: 3.0b3
     License: GPL-2.0+
      Origin: kile-origin
  Collection: 
Installation: user
   Installed: 187,8 MB
     Runtime: org.kde.Platform/x86_64/5.15-23.08
         Sdk: org.kde.Sdk/x86_64/5.15-23.08

      Commit: 6adb7b37321ebe97cad6b60efc7e2ec19c392376330c5e65d442988616a50edf
      Parent: 3e5ab0d985fbdf71a64c61b84e25264106537e9a78d9281dd485c831121a93d3
     Subject: Export org.kde.kile
        Date: 2023-11-21 00:19:24 +0000
```

**Pull request merged**
